kafka-broker/kafka-broker-install.sh

Signed-off-by: Daniel Hill <danhill@digital.uc.dwp.gov.uk>

remove `-y` from pip install

---

dks-host/dks-host-install.sh

Adding AWS-CLI to the packer build process for DKS

Install aws-cli

---

dks-host/dks-host-install.sh

export local/bin path for ec2-user

export local/bin path for ec2-user

---

dks-host/dks-host-install.sh
hbase-to-mongo-export/htme-host-install.sh
snapshot-sender/snapshot-sender_install.sh

DW-2860: Fix versions so we guarantee we get the right ones with matching exponential backoffs in HSM/DKS retries.

DW-2860-pin-versions-for-exponential-backoff-retry

---

dw-general-ami/generic_packer_template.json.j2

an correct shell provisioner syntax

move shell inline provisioners to separate block

---

dw-general-ami/dw-general-ami-install.sh

Reverts dwp/ami-builder-configs#89

Revert "Add conditional for pip and proxy"

---

dw-general-ami/dw-general-ami-install.sh

this only appears to be an issue in older versions of pip

generate http proxy addres for pip without http

---

dw-general-ami/dw-general-ami-install.sh
dw-general-ami/generic_packer_template.json.j2

Working on fix to pip

---

dw-general-ami/dw-general-ami-install.sh

Trying to reduce time of AMI generation

---

dw-general-ami/generic_packer_template.json.j2

change conditionals around commas to ensure that any combination of `provision_scripts` and `provision_script_keys` can be set

move proxy env vars to each provisioner

---

dw-general-ami/dw-general-ami-install.sh

move ssm to be first, add printenv

---

dw-general-ami/dw-general-ami-install.sh
dw-general-ami/generic_packer_template.json.j2

💢 env vars are not passing through to the `dw-general-ami-install.sh`

return to setting proxy confs in provisioner

---

dw-general-ami/dw-general-ami-install.sh

oh how I wish yum would support no_proxy, but clearly that's far too much to ask of a package manager 💢

temporarily remove proxy in yum for SSM install

---

dw-general-ami/dw-general-ami-install.sh

Reverts dwp/ami-builder-configs#114

Revert "cat out yum conf to debug"

---

hbase-to-mongo-export/htme-host-install.sh

DW-2431 end-to-end tests use latest versions

DW-2431 end-to-end tests use latest versions

---

snapshot-sender/snapshot-sender_install.sh

DW-2513-snapshotsender-sends-once version bump to new sender

DW-2513-snapshotsender-sends-once version bump to new sender

---

dks-host/dks-host-install.sh
dks-host/generic_packer_template.json.j2
dw-general-ami/dw-general-ami-install.sh
dw-general-ami/generic_packer_template.json.j2
hbase-to-mongo-export/generic_packer_template.json.j2
hbase-to-mongo-export/htme-host-install.sh
hsm-client/generic_packer_template.json.j2
hsm-client/hsm-client_install.sh
kafka-broker/generic_packer_template.json.j2
kafka-broker/kafka-broker-install.sh
snapshot-sender/generic_packer_template.json.j2
snapshot-sender/snapshot-sender_install.sh

align build scripts to behave the same way and all have the same proxy settings and similar installs

align build scripts to behave the same way

---

dw-general-ami/dw-general-ami-install.sh
dw-general-ami/generic_packer_template.json.j2
dw-general-ami/hardening.sh
dw-general-ami/user_data.sh

Dw 2863 generic ami hardening

---

dw-general-ami/generic_packer_template.json.j2
dw-hardened-ami/generic_packer_template.json.j2

Set Launch Root Volume size
Amended User data script file location

Cjc dw 2863 hardening launch volume size

---

dw-general-ami/generic_packer_template.json.j2
dw-hardened-ami/generic_packer_template.json.j2

Remove Extra volume from AMI prep launch.

Remove extra launch volume

---

dw-general-ami/dw-general-ami-install.sh
dw-general-ami/generic_packer_template.json.j2
dw-hardened-ami/generic_packer_template.json.j2

fixing typoes on User data scripts.
Patch instance during general AMI production

Cjc dw 2863 hardening user data typo

---

dw-general-ami/generic_packer_template.json.j2

Unable to locate file during build, reverting one that didnt throw this error

reverting the update for user data file location

---

dw-hardened-ami/generic_packer_template.json.j2

Signed-off-by: Daniel Hill <danhill@digital.uc.dwp.gov.uk>

add support for source AMI IDs and make source AMI filters variables

---

dw-hardened-ami/dw-hardened-ami-install.sh

ensured that scripts are matching in provision script (Except yum update) to ensure that changes are carried, once confirmed the duplicate steps can be removed.

backfilled changes to hardened ami shell script, part 1

---

dw-hardened-ami/hardening.sh

DW-3657 - Adding back a quarter of the hardening to test EMR

---

dw-hardened-ami/hardening.sh

DW-3657 - Removing chunk that is believed to have broken EMR and adding back in rest

---

dw-hardened-ami/hardening.sh

DW-3657 - Add back more hardening to passing test

---

dw-hardened-ami/hardening.sh

DW-3657 - Add back more hardening to passing test part deux

---

dw-hardened-ami/hardening.sh

DW-3657 - Add back all except what is believed to be the suspect lines

---

dw-hardened-ami/hardening.sh

DW-3657 - Add back some more hardening script

---

dw-hardened-ami/hardening.sh

DW-3657 - Adding back in one of the two directives now causing problem

---

dw-hardened-ami/hardening.sh

DW-3657 - Inversion of previous test due to cluster deployment failure

---

dw-hardened-ami/hardening.sh

DW-3657 - Returning hardening script to normal now that the problem has been found

---

dw-emr-ami/dw-emr-ami-install.sh

DW-3657 - Loosening EMR AMI umask to test

---

dw-ecs-ami/dw-ecs-ami-install.sh
dw-ecs-ami/generic_packer_template.json.j2

* Using hardened base image
* Install ecs-agent as per docs - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-amazonlinux

[DW-4194] Add AMI config for ECS

---

dw-al2-ecs-ami/dw-ecs-ami-install.sh

DW-4842 - ECS AL2 AMI

---

dw-al2-concourse-ami/dw-concourse-ami-install.sh
dw-al2-concourse-ami/generic_packer_template.json.j2

Config to build AL2 Concourse AMI

Concourse AL2

---

README.md

I want to make your docs better for reading

Make your docs better, please accept this PR ❤️

---

ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml

Removed jijna2 template update triggers from all AMIs but base.

Only base should update due to jinja2 template changes

---

ci/infra/meta.yml
dw-al2-base-ami/dw-base-ami-install.sh
generic_packer_template.json.j2

using `use_env_var_file` to replace cat'ing to `/etc/environment`

use use_env_var_file

---

ci/infra/jobs/build_amis/dw-al2-base-ami.yml
ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml
ci/infra/resources.yml

Signed-off-by: danhill <danhill@digital.uc.dwp.gov.uk>

normalise duplicate resources for the generic_packer_template.json.j2

---

ci/infra/jobs/build_amis/dw-al2-base-ami.yml

Signed-off-by: danhill <danhill@digital.uc.dwp.gov.uk>
This will also ensure that it isn't triggered twice by the same PR and that it doesn't attempt to update a non existent PR

normalise PR resources for base ami PR job and track generic template

---

ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml

bumps the concourse version to 6.6.0

---

ci/infra/jobs/build_amis/dw-al2-base-ami.yml
ci/infra/meta.yml

DW-5109 - Missing get from PR job for AL2 AMI

---

dw-al2-base-ami/dw-base-ami-install.sh
dw-general-ami/dw-general-ami-install.sh

Latest ACM-PCM cert retrivor

---

dw-al2-base-ami/dw-base-ami-install.sh
dw-general-ami/dw-general-ami-install.sh

Latest cert retriver

---

dw-al2-base-ami/dw-base-ami-install.sh
dw-general-ami/dw-general-ami-install.sh

Build images with latest cert gen

Build images with latest cert gen

---

dw-al2-base-ami/dw-base-ami-install.sh
dw-general-ami/dw-general-ami-install.sh

Install retrying

---

dw-al2-base-ami/dw-base-ami-install.sh

Install with pip as well as pip3

Install with pip as well as pip3

---

dw-al2-base-ami/dw-base-ami-install.sh
dw-general-ami/dw-general-ami-install.sh

Cert retriever v41

---

dw-al2-base-ami/dw-base-ami-install.sh

Fix paths in AMI

---

ci/infra/jobs/build_amis/dw-al2-hardened-ami-arm.yml

Fix naming of PR task for ARM

---

ci/infra/resource_types.yml

Updating container image repository

---

ci/infra/groups.yml
ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/jobs/build_amis/dw-al2-kafka-ami.yml
ci/infra/meta.yml
ci/infra/resources.yml

- Added testing gates for all AMIs built from the hardened AMI
- Added validate test job
- Added first resource to test validation

Untested ami pipeline

---

README.md
ci/infra/groups.yml
ci/infra/jobs/build_amis/dw-al2-base-ami-arm.yml
ci/infra/jobs/build_amis/dw-al2-base-ami.yml
ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml
ci/infra/jobs/build_amis/dw-al2-kafka-ami.yml
ci/infra/meta.yml
ci/infra/resource_types.yml
ci/infra/resources.yml
dw-al2-kafka-ami/dw-kafka-ami-install.sh

* README updates
* Correction to group names
* Consolidation of resources
* Using file output resources to pass AMI ID

Dw 4696 using ami ids as pipeline resources

---

ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
ci/infra/jobs/build_amis/dw-al2-kafka-ami.yml
ci/infra/resources.yml

Using the successful EMR pattern, and replicating that across the rest of the AMIs.

Other AMIs now match EMR pattern

---

ci/infra/groups.yml
ci/infra/jobs/build_amis/dw-al2-nginx-ami.yml
ci/infra/resources.yml
dw-al2-nginx-ami/dw-nginx-ami-install.sh

Nginx AMI for BGDC integration

dw-6460 initial commit to create nginx-ami for bgdc integration

---

ci/infra/groups.yml
ci/infra/jobs/build_amis/update-pipeline.yml
ci/infra/meta.yml
ci/infra/resources.yml

add update-pipeline job

---

ci/infra/jobs/build_amis/update-pipeline.yml

Fix update-pipeline

---

ci/infra/groups.yml
ci/infra/jobs/build_amis/dw-al2-hbase-ami-arm.yml
ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml
ci/infra/resources.yml
dw-al2-hbase-ami/dw-hbase-ami-install.sh

Create Hbase AMI

---

ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml

Fix Hbase AMI config file location

---

ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/resources.yml

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

check if emr ami consumers passed

---

ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/resources.yml

Pass concourse test result to validate job

use concourse test result

---

ci/infra/groups.yml
ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml
ci/infra/resources.yml
dw-al2-jvm-ami/dw-jvm-ami-install.sh

Create test pipelines for JVM AMI
Currently no differences for JVM AMI vs. hardened AMI so construction script is "hello world".

Create test pipelines for JVM AMI

---

ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml
ci/infra/resources.yml

Snapshot sender requirement for JVM AMI

---

ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml
ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml
ci/infra/resources.yml

Add consumers for JVM and Hbase AMI test validation

---

ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/resources.yml

adding uc feature which is a consumer of the EMR AMI

adding uc feature emr ami aconsumer

---

ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/resources.yml

Add CYI ami test

---

ci/infra/groups.yml
ci/infra/jobs/build_amis/dw-al2-analytical-env-emr-ami.yml
ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml
ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml
ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml
ci/infra/jobs/build_amis/dw-al2-kafka-ami.yml
ci/infra/resources.yml

Start tests after 7pm

---

dw-al2-jvm-ami/dw-jvm-ami-install.sh

update `iptables` to default to accept anything that wasn't specifically covered by sg-rules

update iptables to accept anything not covered in sg-rules

---

ci/infra/jobs/build_amis/dw-al2-hcs-backed-ami.yml
ci/infra/jobs/build_amis/dw-al2-hcs-backed-singlevol-ami.yml
ci/infra/resources.yml

[DTWRKS-1146] - Change the source HCS AMI for dualvol backed AMI images
[DTWRKS-1147] - Change the source HCS AMI for single vol backed AMI images

Change the source HCS AMI for dualvol and  single vol backed AMI images
