dwp/ami-builder-configs

- dks-host/dks-host-install.sh
sudo echo "PATH=/usr/local/aws/bin:$PATH" > /etc/profile.d/aws.sh
sudo chmod +x /etc/profile.d/aws.sh
> path fix for aws-cli to make permanent in Centos7

- dks-host/dks-host-install.sh
Install the AWS CloudHSM Client and Command Line Tools to EC2 on same subnet to enable connect to a CloudHSM cluster
> Install the AWS CloudHSM Client and Command Line Tools

- dks-host/dks
Removing DAEMON_OPTS="/opt/dks/server.properties" as this hardcoded properties file is not required, DKS will search in /opt/dks/config for an application.properties file.
> DW-2491 - Removing DAEMON_OPTS

- dw-general-ami/generic_packer_template.json.j2
usage of env vars in packer templates is restricted to variables block
https://www.packer.io/docs/templates/user-variables.html#environment-variables
> move `env`s to a variables block

- dw-general-ami/generic_packer_template.json.j2
Because CentOS7 wants it in /etc/environment
> Change file for proxy config

- dw-general-ami/generic_packer_template.json.j2
pip seems to want an env var or passing on command line.
> Giving pip access to proxy

- dw-general-ami/dw-general-ami-install.sh
VPC endpoints are region-specific, but the SSM agent RPM lives in us-east-1.
Therefore, download the SSM RPM via the Internet Proxy using YUM's standard
proxy config.
> Install SSM agent via the Internet Proxy

- dw-general-ami/dw-general-ami-install.sh
This ensures we always use the same mirror so that we can get through the proxy
> Use fixed YUM repos instead of mirror lists

- dw-general-ami/dw-general-ami-install.sh
- dw-general-ami/generic_packer_template.json.j2
- dw-hardened-ami/generic_packer_template.json.j2
Override was breaking stuff as it was using Centos, removed the override so its always the latest amazon 64bit HVM EBS
> Removed override for Source AMI Name

- dw-general-ami/dw-general-ami-install.sh
- dw-general-ami/generic_packer_template.json.j2
- dw-general-ami/user_data.txt
- dw-hardened-ami/dw-hardened-ami-install.sh
- dw-hardened-ami/generic_packer_template.json.j2
- dw-hardened-ami/user_data.sh
- dw-hardened-ami/user_data.txt
* Amazon Linux attempts a yum update on first boot, this holds the yum pid lock open so provision scripts cannot complete (results in ami build failure)
* Removed the auto_update on instance boot after rebundling to an AMI
> Cjc dw 2863 hardening user data scripts

- dw-general-ami/generic_packer_template.json.j2
Referring to wrong location (remote) for the userdata file, this should be local to the template when packer runs.
> correcting location of AMI userdata file

- dw-general-ami/dw-general-ami-install.sh
Amazon Linux 1 already contains the `awscli` package, but at an
old version.  `pip` won't install a newer version unless provided
the `--upgrade` flag
> Force awscli package to be upgraded

- dw-general-ami/dw-general-ami-install.sh
- dw-general-ami/generic_packer_template.json.j2
- dw-general-ami/user_data.txt
- dw-hardened-ami/generic_packer_template.json.j2
- dw-hardened-ami/user_data.txt
YUM will need to have the proxy set to the correct value based on which env
the instance is being launched in (e.g. management-dev proxy for dev instances,
management proxy for production instances).
We lay down a simple(ish) shell script that retrieves the proxy endpoint
specified in the `internet_proxy` instance tag, then configure the proxy for
each individual YUM repo that needs it.
Note that we explicitly *don't* set a global YUM default proxy in /etc/yum.conf
because repositories that are laid down on the instances themselves (e.g. EMR)
could well be S3 based, and therefore *mustn't* use the proxy.
> Configure YUM proxy on instance launch

- dw-general-ami/dw-general-ami-install.sh
EMR specifies a `runcmd` section in the userdata of the instances that it
spins up. That overrides any `runcmd` sections we have on disk. Instead,
specify that the yum proxy setting script be run during `bootcmd` instead.
This is much earlier than we'd generally want things like this to be run,
but the default AL1 AMI doesn't specify any `bootcmd` sections, neither does
EMR's userdata so we avoid any conflicts/overrides by doing things this way.
> Enable YUM proxy setting to run under EMR

- dw-hardened-ami/hardening.sh
The generic hardened AMI should be as locked down as possible; a separate AMI
will be built specifically for EMR which will turn these back off again.
> Add back SELinux enforcing config and umask tightening

- dw-hardened-ami/dw-hardened-ami-install.sh
CloudWatch has been configured to alert if any DEBUG level messages are
enabled in Production, because application logs at that level could leak
sensitive information.
Amazon Linux configures Cloud-Init with DEBUG logs by default, which ends up
triggering the CloudWatch alerts. Change it to INFO to avoid the false alerts.
> DW-3096: Turn down Cloud-Init's logging

- dw-general-ami/generic_packer_template.json.j2
Reverts dwp/ami-builder-configs#203 as EMR found to be incompatible with io1 root volumes
> Revert "Change General AMI volume type to io1"

- dw-hardened-ami/hardening.sh
Literally just chopping the hardening script in half in order to build an AMI for testing in EMR, to debug why EMR will not spin-up on this AMI (EMR itself doesn't provide sufficient debugging output for this).
> DW-3657 - Reduce hardening script to test EMR

- dw-hardened-ami/hardening.sh
> DW-3657 - Previous test EMR failed to start, so removing four of the eight possible causes

- dw-al2-emr-ami/dw-emr-ami-install.sh
- dw-al2-emr-ami/generic_packer_template.json.j2
Tested with EMR 5.30.1
An EMR cluster using this AMI will require a custom bootstrap action to start the SSM agent as Amazon-provided Systemd unit named "setup-devices" fails to do so. Bootstrap action example:
```
#!/bin/bash  
sudo /bin/systemctl start amazon-ssm-agent
```
> Add AL2 EMR AMI

- dw-al2-general-ami/dw-general-ami-install.sh
> DW-4957 - Migrate CloudWatch Agent installation to AMI

- dw-al2-concourse-ami/dw-concourse-ami-install.sh
- dw-al2-concourse-ami/generic_packer_template.json.j2
This improves the templating, allowing the Concourse version to be controlled by the pipeline that builds the Concourse AMI.
> Templating for Concourse version to be controlled by the pipeline

- ci/infra/meta.yml
- generic_packer_template.json.j2
This breaks things when instances are launched because they'll not
be able to reach the proxy endpoint that Packer can when building.
> Don't set proxy in system-wide environment

- ci/infra/jobs/build_amis/dw-al2-base-ami.yml
- ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
- ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
- ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
- ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml
- ci/infra/meta.yml
- generic_packer_template.json.j2
In order for each AMI to build correctly, they need the latest version template.  But changes to the template should only trigger builds on the base image.
This way seemed most sane to me.
> Add template as resource, fix template for multiple scripts

- ci/infra/jobs/build_amis/dw-al2-base-ami.yml
- ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
- ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml
- ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
- ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml
Pipeline changes should be able to trigger builds when no AMI config changes have been made.
> Allow pipeline config changes to trigger builds

- dw-al2-ecs-ami/dw-ecs-ami-install.sh
In order to be able to mount S3 as a volume, we need to install `s3fs-fuse`
> install s3fs

- dw-al2-emr-ami/dw-emr-ami-install.sh
Don't need to set this the default of `65536` is "enough" according to AWS.
> nonono ulimit

- ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml
Fixes the Concourse AMI build pipeline.  It previously was not passing the tarball to the build step.
Bumps Concourse to `v7.2.0`
> fix concourse ami pipeline, bump to 7.2.0

- ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml
- ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml
- ci/infra/meta.yml
- ci/infra/resources.yml
- awkward multiple ami testing in a single pipeline, makes for awkward inputs.
> Fix inputs to new tests

- ci/infra/jobs/build_amis/dw-al2-analytical-env-emr-ami.yml
- dw-al2-analytical-env-emr-ami/dw-al2-analytical-env-emr-ami-install.sh
oddly the analytical-env emr uses [this script](https://github.com/dwp/aws-analytical-env/blob/master/terraform/modules/emr/templates/emr/py_pckgs_install.sh) as bootstrap action which installs mostly same pkgs apart from below difference -
`
dfply==0.3.3
dplython==0.0.7
PyDriller==2.0
pandas==1.2.5
so, best is to put them into a single place instead.
> collates python packages into single file

- ci/infra/jobs/build_amis/dw-al2-analytical-env-emr-ami.yml
- ci/infra/jobs/build_amis/dw-al2-base-ami.yml
- ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml
- ci/infra/resources.yml
- dw-al2-analytical-env-emr-ami/dw-al2-analytical-env-emr-ami-install.sh
- adds a resource for tested emr ami-id
- builds `analytical-env` ami using tested emr-ami
- maps correct ami for pr job
- moves out-of-hours job into base pipeline
> builds analytical-env ami using tested emr-ami
